// Generated by gencpp from file cs_msgs/Images.msg
// DO NOT EDIT!


#ifndef CS_MSGS_MESSAGE_IMAGES_H
#define CS_MSGS_MESSAGE_IMAGES_H

#include <ros/service_traits.h>


#include <cs_msgs/ImagesRequest.h>
#include <cs_msgs/ImagesResponse.h>


namespace cs_msgs
{

struct Images
{

typedef ImagesRequest Request;
typedef ImagesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Images
} // namespace cs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cs_msgs::Images > {
  static const char* value()
  {
    return "91be00f47290e385ef09fee48611aeee";
  }

  static const char* value(const ::cs_msgs::Images&) { return value(); }
};

template<>
struct DataType< ::cs_msgs::Images > {
  static const char* value()
  {
    return "cs_msgs/Images";
  }

  static const char* value(const ::cs_msgs::Images&) { return value(); }
};


// service_traits::MD5Sum< ::cs_msgs::ImagesRequest> should match
// service_traits::MD5Sum< ::cs_msgs::Images >
template<>
struct MD5Sum< ::cs_msgs::ImagesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cs_msgs::Images >::value();
  }
  static const char* value(const ::cs_msgs::ImagesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs_msgs::ImagesRequest> should match
// service_traits::DataType< ::cs_msgs::Images >
template<>
struct DataType< ::cs_msgs::ImagesRequest>
{
  static const char* value()
  {
    return DataType< ::cs_msgs::Images >::value();
  }
  static const char* value(const ::cs_msgs::ImagesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cs_msgs::ImagesResponse> should match
// service_traits::MD5Sum< ::cs_msgs::Images >
template<>
struct MD5Sum< ::cs_msgs::ImagesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cs_msgs::Images >::value();
  }
  static const char* value(const ::cs_msgs::ImagesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs_msgs::ImagesResponse> should match
// service_traits::DataType< ::cs_msgs::Images >
template<>
struct DataType< ::cs_msgs::ImagesResponse>
{
  static const char* value()
  {
    return DataType< ::cs_msgs::Images >::value();
  }
  static const char* value(const ::cs_msgs::ImagesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CS_MSGS_MESSAGE_IMAGES_H
