// Generated by gencpp from file cs_msgs/LocationResponse.msg
// DO NOT EDIT!


#ifndef CS_MSGS_MESSAGE_LOCATIONRESPONSE_H
#define CS_MSGS_MESSAGE_LOCATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cs_msgs
{
template <class ContainerAllocator>
struct LocationResponse_
{
  typedef LocationResponse_<ContainerAllocator> Type;

  LocationResponse_()
    : station(0)  {
    }
  LocationResponse_(const ContainerAllocator& _alloc)
    : station(0)  {
  (void)_alloc;
    }



   typedef int8_t _station_type;
  _station_type station;





  typedef boost::shared_ptr< ::cs_msgs::LocationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cs_msgs::LocationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LocationResponse_

typedef ::cs_msgs::LocationResponse_<std::allocator<void> > LocationResponse;

typedef boost::shared_ptr< ::cs_msgs::LocationResponse > LocationResponsePtr;
typedef boost::shared_ptr< ::cs_msgs::LocationResponse const> LocationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cs_msgs::LocationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cs_msgs::LocationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cs_msgs::LocationResponse_<ContainerAllocator1> & lhs, const ::cs_msgs::LocationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.station == rhs.station;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cs_msgs::LocationResponse_<ContainerAllocator1> & lhs, const ::cs_msgs::LocationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cs_msgs::LocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cs_msgs::LocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_msgs::LocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_msgs::LocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_msgs::LocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_msgs::LocationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cs_msgs::LocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b988d96a32f6b6cc755554dfacda684";
  }

  static const char* value(const ::cs_msgs::LocationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b988d96a32f6b6cULL;
  static const uint64_t static_value2 = 0xc755554dfacda684ULL;
};

template<class ContainerAllocator>
struct DataType< ::cs_msgs::LocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cs_msgs/LocationResponse";
  }

  static const char* value(const ::cs_msgs::LocationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cs_msgs::LocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 station #Station Location\n"
"\n"
;
  }

  static const char* value(const ::cs_msgs::LocationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cs_msgs::LocationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.station);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cs_msgs::LocationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cs_msgs::LocationResponse_<ContainerAllocator>& v)
  {
    s << indent << "station: ";
    Printer<int8_t>::stream(s, indent + "  ", v.station);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CS_MSGS_MESSAGE_LOCATIONRESPONSE_H
