// Generated by gencpp from file cs_msgs/Location.msg
// DO NOT EDIT!


#ifndef CS_MSGS_MESSAGE_LOCATION_H
#define CS_MSGS_MESSAGE_LOCATION_H

#include <ros/service_traits.h>


#include <cs_msgs/LocationRequest.h>
#include <cs_msgs/LocationResponse.h>


namespace cs_msgs
{

struct Location
{

typedef LocationRequest Request;
typedef LocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Location
} // namespace cs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cs_msgs::Location > {
  static const char* value()
  {
    return "ccef7d34db997b060fe172638f5b079f";
  }

  static const char* value(const ::cs_msgs::Location&) { return value(); }
};

template<>
struct DataType< ::cs_msgs::Location > {
  static const char* value()
  {
    return "cs_msgs/Location";
  }

  static const char* value(const ::cs_msgs::Location&) { return value(); }
};


// service_traits::MD5Sum< ::cs_msgs::LocationRequest> should match
// service_traits::MD5Sum< ::cs_msgs::Location >
template<>
struct MD5Sum< ::cs_msgs::LocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cs_msgs::Location >::value();
  }
  static const char* value(const ::cs_msgs::LocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs_msgs::LocationRequest> should match
// service_traits::DataType< ::cs_msgs::Location >
template<>
struct DataType< ::cs_msgs::LocationRequest>
{
  static const char* value()
  {
    return DataType< ::cs_msgs::Location >::value();
  }
  static const char* value(const ::cs_msgs::LocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cs_msgs::LocationResponse> should match
// service_traits::MD5Sum< ::cs_msgs::Location >
template<>
struct MD5Sum< ::cs_msgs::LocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cs_msgs::Location >::value();
  }
  static const char* value(const ::cs_msgs::LocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cs_msgs::LocationResponse> should match
// service_traits::DataType< ::cs_msgs::Location >
template<>
struct DataType< ::cs_msgs::LocationResponse>
{
  static const char* value()
  {
    return DataType< ::cs_msgs::Location >::value();
  }
  static const char* value(const ::cs_msgs::LocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CS_MSGS_MESSAGE_LOCATION_H
