// Generated by gencpp from file cs_msgs/QualityResponse.msg
// DO NOT EDIT!


#ifndef CS_MSGS_MESSAGE_QUALITYRESPONSE_H
#define CS_MSGS_MESSAGE_QUALITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cs_msgs
{
template <class ContainerAllocator>
struct QualityResponse_
{
  typedef QualityResponse_<ContainerAllocator> Type;

  QualityResponse_()
    : confirmation()  {
    }
  QualityResponse_(const ContainerAllocator& _alloc)
    : confirmation(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _confirmation_type;
  _confirmation_type confirmation;





  typedef boost::shared_ptr< ::cs_msgs::QualityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cs_msgs::QualityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QualityResponse_

typedef ::cs_msgs::QualityResponse_<std::allocator<void> > QualityResponse;

typedef boost::shared_ptr< ::cs_msgs::QualityResponse > QualityResponsePtr;
typedef boost::shared_ptr< ::cs_msgs::QualityResponse const> QualityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cs_msgs::QualityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cs_msgs::QualityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cs_msgs::QualityResponse_<ContainerAllocator1> & lhs, const ::cs_msgs::QualityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.confirmation == rhs.confirmation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cs_msgs::QualityResponse_<ContainerAllocator1> & lhs, const ::cs_msgs::QualityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cs_msgs::QualityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cs_msgs::QualityResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_msgs::QualityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_msgs::QualityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_msgs::QualityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_msgs::QualityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cs_msgs::QualityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fdcda0f95399f6b72fea1643acc7e4b";
  }

  static const char* value(const ::cs_msgs::QualityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fdcda0f95399f6bULL;
  static const uint64_t static_value2 = 0x72fea1643acc7e4bULL;
};

template<class ContainerAllocator>
struct DataType< ::cs_msgs::QualityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cs_msgs/QualityResponse";
  }

  static const char* value(const ::cs_msgs::QualityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cs_msgs::QualityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string confirmation #return confirmation\n"
"\n"
;
  }

  static const char* value(const ::cs_msgs::QualityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cs_msgs::QualityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confirmation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QualityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cs_msgs::QualityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cs_msgs::QualityResponse_<ContainerAllocator>& v)
  {
    s << indent << "confirmation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.confirmation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CS_MSGS_MESSAGE_QUALITYRESPONSE_H
