// Generated by gencpp from file cs_msgs/QualityRequest.msg
// DO NOT EDIT!


#ifndef CS_MSGS_MESSAGE_QUALITYREQUEST_H
#define CS_MSGS_MESSAGE_QUALITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cs_msgs
{
template <class ContainerAllocator>
struct QualityRequest_
{
  typedef QualityRequest_<ContainerAllocator> Type;

  QualityRequest_()
    : ID(0)
    , result(0)  {
    }
  QualityRequest_(const ContainerAllocator& _alloc)
    : ID(0)
    , result(0)  {
  (void)_alloc;
    }



   typedef int8_t _ID_type;
  _ID_type ID;

   typedef int8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::cs_msgs::QualityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cs_msgs::QualityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QualityRequest_

typedef ::cs_msgs::QualityRequest_<std::allocator<void> > QualityRequest;

typedef boost::shared_ptr< ::cs_msgs::QualityRequest > QualityRequestPtr;
typedef boost::shared_ptr< ::cs_msgs::QualityRequest const> QualityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cs_msgs::QualityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cs_msgs::QualityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cs_msgs::QualityRequest_<ContainerAllocator1> & lhs, const ::cs_msgs::QualityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ID == rhs.ID &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cs_msgs::QualityRequest_<ContainerAllocator1> & lhs, const ::cs_msgs::QualityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cs_msgs::QualityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cs_msgs::QualityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_msgs::QualityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs_msgs::QualityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_msgs::QualityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs_msgs::QualityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cs_msgs::QualityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3af964c7233a2a761d68ebfbf232f725";
  }

  static const char* value(const ::cs_msgs::QualityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3af964c7233a2a76ULL;
  static const uint64_t static_value2 = 0x1d68ebfbf232f725ULL;
};

template<class ContainerAllocator>
struct DataType< ::cs_msgs::QualityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cs_msgs/QualityRequest";
  }

  static const char* value(const ::cs_msgs::QualityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cs_msgs::QualityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ID #Product ID\n"
"int8 result #Percentage match\n"
;
  }

  static const char* value(const ::cs_msgs::QualityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cs_msgs::QualityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QualityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cs_msgs::QualityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cs_msgs::QualityRequest_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CS_MSGS_MESSAGE_QUALITYREQUEST_H
